#!/bin/sh

# Change `style.css` or `style.min.css` to whatever you would like your compiled
# stylesheet to be called. Do not rename `style.scss` or alter references to it.

# No minification
sass --watch _scss/style.scss:css/style.css --style expanded --precision 10

#sass --watch _scss/style.scss:css/style.css --style compressed


exit 0
